### ISSUE TITLE
一句话：牛

### ISSUE THREAD

**Issue by cricklew** [lxzmads/zsxqbackup#2]

**Comment by cricklew** [comment]
文件怎么批量下载不了呀

**Comment by lxzmads** [comment]
我这边测试没问题呀，可以把错误日志发上来看一下

**Comment by cricklew** [comment]
老哥，谢谢你，我之前搞好了，设置错了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年9月4日(周六) 中午1:50
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [lxzmads/zsxqbackup] 一句话：牛 (#2)




 
我这边测试没问题呀，可以把错误日志发上来看一下
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
